---
- name: Instalar Pip para gerenciar pacotes python
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3-pip
    state: present


- name: Instala módulos Python com Pip
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ packages}}"