---
# Executar a importação desses playbooks apenas se o servidor nunca tiver sido configurado. Caso servidor já exista e esteje configurado, ignorar esses playbooks.
####
- name: Inclui playbook de configurações iniciais do servidor
  ansible.builtin.import_playbook: 
    config-server.yaml

- name: Configuração do LEMP
  ansible.builtin.import_playbook:
    lemp-server.yaml
####

- name: Cria ambiente wordpress
  hosts: all
  become: true
  gather_facts: false

  roles:
    - wordpress

  vars_prompt:
    - name: user_wordpress
      prompt: "Qual o usuário para executar o wordpress?"
      private: false

    - name: nome_projeto
      prompt: Qual o nome do projeto?
      private: false

    - name: php_version
      prompt:  Qual versão do PHP para o projeto?
      private: false

    - name: mysql_admin
      prompt: "Qual o usuário admin do MySQL?"
      private: false

    - name: mysql_admin_pwd
      prompt: Qual a senha do usuário admin do MySQL?
      confirm: true
      private: true      

    - name: db_name
      prompt: Qual o nome do banco de dados?
      private: false

    - name: db_user
      prompt: Qual o nome do usuário do banco de dados?
      private: false

    - name: db_user_pwd
      prompt: Qual a senha do usuário do banco de dados?
      private: true
      confirm: true

    - name: nginx_domain
      prompt: Qual será o domínio utilizado no projeto?
      private: false
    
