---
- name: Copia template Nginx do site
  ansible.builtin.template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ nginx_domain }}"

- name: Cria link para sites-enabled
  ansible.builtin.file:
    state: link
    src: "/etc/nginx/sites-available/{{ nginx_domain }}"
    path: "/etc/nginx/sites-enabled/{{ nginx_domain }}"
    group: "{{ user_wordpress }}"
    owner: "{{ user_wordpress }}"

- name: Reinicia Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted