---
- name: Instalar MySQL
  ansible.builtin.apt:
    update_cache: true
    name:
      - mysql-server
      - mysql-client
    state: present


- name: Setar senha para usuário root
  ansible.builtin.shell: |
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{  mysql_admin_pwd  }}';"


- name: Alterar configurações MySQL com template
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

    
- name: Reiniciar MySQL
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: restarted
