---
- name: Instalação Nginx
  ansible.builtin.apt:
    update_cache: true
    name:
      - nginx
    state: present


- name: Copia template configuração Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf


- name: Reiniciar serviço Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true     