---
- name: Instalação Software-Properties-Common
  ansible.builtin.apt:
    name:
      - software-properties-common
    update_cache: true
    state: present


- name: Adicionar repositório PHP
  ansible.builtin.apt_repository:
    repo: "{{ php_repository }}"
    state: present
    update_cache: true


- name: Instalação PHP-FPM e módulos
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop: "{{ php_modules }}"


- name: Configuração PHP utilizando template
  ansible.builtin.template:
    src: php.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/php.ini


- name: Reiniciar o serviço do PHP-FPM
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
    enabled: true