- name: Criação de usuário
  hosts: all
  remote_user: root
  vars_files:
   - ./vars.yml
  tasks:
    - name: Instalação do pacote WHOIS
      ansible.builtin.apt:
        name: whois
        state: present
        #Atualiza a lista de repositórios
        update_cache: true
    - name: Gerar a senha criptografada
      ansible.builtin.shell: "mkpasswd --method=sha-512 {{ senha }}"
      register: cripto_pwd
    - name: Criar o usuário no Linux
      ansible.builtin.user:
        name: "{{ usuario }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        #passa a saída do register, apenas campo da senha
        password: "{{ cripto_pwd.stdout }}"
    - name: Criar o diretório SSH
      ansible.builtin.file:
        path: "/home/{{ usuario }}/.ssh"
        state: directory
        group: "{{ usuario }}"
        owner: "{{ usuario }}"
        #cria diretório de forma recursiva
        recurse: true
    - name: Copia chave SSH para authorized keys
      ansible.builtin.copy:
        src: CAMINHO DA CHAVE
        dest: "/home/{{ usuario }}/.ssh/authorized_keys"
        