---
- name: Download e descompactar arquivos Wordpress
  ansible.builtin.unarchive:
    src: "{{ wordpress_url }}"
    dest: "{{ nginx_dir }}"
    remote_src: yes
    group: "{{ nome_projeto }}"
    mode: '755'
    owner: "{{ nome_projeto }}"


- name: Renomeia a pasta wordpress para o nome do projeto
  ansible.builtin.shell: |
    mv "{{ nginx_dir }}/wordpress"  "{{ nginx_dir }}/{{ nome_projeto }}"


- name: Cria o banco de dados do Wordpress
  community.mysql.mysql_db:
    login_unix_socket: /run/mysqld/mysqld.sock
    login_host: localhost
    login_user: "{{ mysql_admin }}"
    login_password: "{{ mysql_admin_pwd }}"
    name: "{{ db_name }}"
    state: present
    

- name: Cria usuário do banco de dados e atribui permissões
  community.mysql.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    login_host: localhost
    login_user: "{{ mysql_admin }}"
    login_password: "{{ mysql_admin_pwd }}"
    name: "{{ db_user }}"
    host: localhost
    password: "{{ db_user_pwd }}"
    priv: "{{ db_name }}.*:ALL,GRANT"
